export const SKILL_LIST_REQUEST = 'SKILL_LIST_REQUEST'
export const SKILL_LIST_SUCCESS = 'SKILL_LIST_SUCCESS'
export const SKILL_LIST_FAIL = 'SKILL_LIST_FAIL'


export const SKILL_DETAILS_REQUEST = 'SKILL_DETAILS_REQUEST'
export const SKILL_DETAILS_SUCCESS = 'SKILL_DETAILS_SUCCESS'
export const SKILL_DETAILS_FAIL = 'SKILL_DETAILS_FAIL'


export const SKILL_DELETE_REQUEST = 'SKILL_DELETE_REQUEST'
export const SKILL_DELETE_SUCCESS = 'SKILL_DELETE_SUCCESS'
export const SKILL_DELETE_FAIL = 'SKILL_DELETE_FAIL'

export const SKILL_CREATE_REQUEST = 'SKILL_CREATE_REQUEST'
export const SKILL_CREATE_SUCCESS = 'SKILL_CREATE_SUCCESS'
export const SKILL_CREATE_FAIL = 'SKILL_CREATE_FAIL'
export const SKILL_CREATE_RESET = 'SKILL_CREATE_RESET'


export const SKILL_UPDATE_REQUEST = 'SKILL_UPDATE_REQUEST'
export const SKILL_UPDATE_SUCCESS ='SKILL_UPDATE_SUCCESS'
export const SKILL_UPDATE_FAIL = 'SKILL_UPDATE_FAIL'
export const SKILL_UPDATE_RESET = 'SKILL_UPDATE_RESET'


export const SKILL_CREATE_REVIEW_REQUEST = 'SKILL_CREATE_REVIEW_REQUEST'
export const SKILL_CREATE_REVIEW_SUCCESS = 'SKILL_CREATE_REVIEW_SUCCESS'
export const SKILL_CREATE_REVIEW_FAIL = 'SKILL_CREATE_REVIEW_FAIL'
export const SKILL_CREATE_REVIEW_RESET = 'SKILL_CREATE_REVIEW_RESET'

export const SKILL_TOP_REQUEST = 'SKILL_TOP_REQUEST'
export const SKILL_TOP_SUCCESS = 'SKILL_TOP_SUCCESS'
export const SKILL_TOP_FAIL = 'SKILL_TOP_FAIL'

